version: '3.4'

services:
  redis:
    image: 'redis'
    volumes:
      - 'redis:/data'

  app:
    tty: true
    stdin_open: true
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - '.:/app'
    depends_on:
      - redis

volumes:
  redis:
